name: 'Configure AWS Authentication'
description: 'Configure AWS credentials for GitHub Actions'

inputs:
  aws-region:
    description: 'AWS Region to use'
    required: true
  role-to-assume:
    description: 'ARN of the role to assume'
    required: true
  role-session-name:
    description: 'Name for the role session'
    required: true
  mask-aws-account-id:
    description: 'Whether to mask the AWS account ID in logs'
    required: false
    default: 'false'

outputs:
  aws_region:
    description: 'The configured AWS region'
    value: ${{ inputs.aws-region }}
  aws_role_arn:
    description: 'The role ARN used for authentication'
    value: ${{ inputs.role-to-assume }}
  aws_account_id:
    description: 'The AWS account ID'
    value: ${{ steps.assume-role.outputs.aws-account-id }}

runs:
  using: "composite"
  steps:
    - id: assume-role
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        mask-aws-account-id: ${{ inputs.mask-aws-account-id }}

    - id: verify-aws-access
      name: Verify AWS access
      shell: bash
      run: |
        aws sts get-caller-identity --query Arn --output text