name: "Deploy images of SciCat backend and MongoDB to AWS in ECR"
run-name: (${{ github.event.inputs.environment }}) Deploy SciCat Backend to AWS by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: 'integration'
        type: choice
        options:
          - integration
          - staging
          - production

permissions:
  contents: read
  id-token: write

jobs:
  scicat-image-to-ecr:
    name: Deploys SciCat Docker Image to ECR
    uses: ./.github/workflows/scicat-image-to-ecr.yml
    concurrency:
      group: environment-${{ github.ref_name }}
      cancel-in-progress: false
    with:
      environment: ${{ github.event.inputs.environment }}
      aws_region: ${{ vars.AWS_REGION || 'eu-west-1' }}
      scicat_image: ghcr.io/scicatproject/backend-next:${{ vars.SCICAT_IMAGE_TAG || 'latest' }}
      role_arn_image_push: ${{ vars.ROLE_ARN_IMAGE_PUSH }}

  mongodb-image-to-ecr:
    name: Deploy MongoDB Container to ECR
    uses: ./.github/workflows/mongodb-image-to-ecr.yml
    needs: [scicat-image-to-ecr] # Wait for the previous job to finish
    concurrency:
      group: environment-${{ github.ref_name }}
      cancel-in-progress: false
    with:
      environment: ${{ github.event.inputs.environment }}
      aws_region: ${{ vars.AWS_REGION || 'eu-west-1' }}
      mongodb_image: mongo:${{ vars.MONGODB_IMAGE_TAG || '6.0.21' }}
      role_arn_image_push: ${{ vars.ROLE_ARN_IMAGE_PUSH }}

  mongo-ecr-to-ecs:
    name: Deploy MongoDB Image from ECR to ECS
    uses: ./.github/workflows/mongodb-ecr-to-ecs.yml
    needs: mongodb-image-to-ecr # Wait for the previous job to finish
    with:
      environment_name: ${{ github.event.inputs.environment }}
      deploy_mode: ${{ vars.DEPLOY_MODE || 'blue-green' }}
      aws_region: ${{ vars.AWS_REGION || 'eu-west-1' }}
      role_arn_ecs: ${{ vars.ROLE_ARN_DEPLOY_ECS }}