name: "Deploy apps in ECS"

# The workflow should only trigger when indirectly invoked
on:
  workflow_call:
    inputs:
      application_container_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      code_deploy_details_ssm_parameter_path:
        required: true
        type: string
      deploy_mode:
        required: true
        type: string
      ecs_cluster_name:
        required: true
        type: string
      ecs_deploy_wait_delay_minutes:
        required: true
        type: number
      ecs_service_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      image_url:
        required: true
        type: string
      role_arn_deploy:
        required: true
        type: string
      task_definition_name:
        required: true
        type: string
      task_template_details_ssm_parameter_path:
        required: true
        type: string

env:
  AWS_REGION: ${{ inputs.aws_region }}

jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
      - id: display-input-variables
        name: Display input variables
        uses: actions/github-script@v4
        with:
          script: |
            console.log("📋 Received Variables:");
            console.log(`application_container_name: ${{ inputs.application_container_name }}`);
            console.log(`aws_region: ${{ inputs.aws_region }}`);
            console.log(`code_deploy_details_ssm_parameter_path: ${{ inputs.code_deploy_details_ssm_parameter_path }}`);
            console.log(`deploy_mode: ${{ inputs.deploy_mode }}`);
            console.log(`ecs_cluster_name: ${{ inputs.ecs_cluster_name }}`);
            console.log(`ecs_deploy_wait_delay_minutes: ${{ inputs.ecs_deploy_wait_delay_minutes }}`);
            console.log(`ecs_service_name: ${{ inputs.ecs_service_name }}`);
            console.log(`environment_name: ${{ inputs.environment_name }}`);
            console.log(`image_url: ${{ inputs.image_url }}`);
            console.log(`role_arn_deploy: ${{ inputs.role_arn_deploy }}`);
            console.log(`task_definition_name: ${{ inputs.task_definition_name }}`);
            console.log(`task_template_details_ssm_parameter_path: ${{ inputs.task_template_details_ssm_parameter_path }}`);